export const SUCCESSFUL_LOGIN = 'SUCCESS_LOGIN';
export const SUCCESSFUL_LOGOUT = 'SUCCESSFUL_LOGOUT';
export const SUCCESSFUL_SIGNUP = 'SUCCESSFUL_SIGNUP';

export const LOGIN_BAD_REQUEST = 'LOGIN_BAD_REQUEST';
export const LOGIN_INVALID_REQUEST = 'LOGIN_INVALID_REQUEST'; 
export const LOGIN_INTERNAL_SERVER_ERROR = 'LOGIN_INTERNAL_SERVER_ERROR';

export const USER_BAD_REQUEST = 'USER_BAD_REQUEST';
export const USER_INVALID_REQUEST = 'USER_INVALID_REQUEST'; 
export const USER_INTERNAL_SERVER_ERROR = 'USER_INTERNAL_SERVER_ERROR';

export const DEALER_BAD_REQUEST = 'DEALER_BAD_REQUEST';
export const DEALER_INVALID_REQUEST = 'DEALER_INVALID_REQUEST'; 
export const DEALER_INTERNAL_SERVER_ERROR = 'DEALER_INTERNAL_SERVER_ERROR';

export const QUOTE_BAD_REQUEST = 'QUOTE_BAD_REQUEST';
export const QUOTE_INVALID_REQUEST = 'QUOTE_INVALID_REQUEST'; 
export const QUOTE_INTERNAL_SERVER_ERROR = 'QUOTE_INTERNAL_SERVER_ERROR';

export const POOL_BAD_REQUEST = 'POOL_BAD_REQUEST';
export const POOL_INVALID_REQUEST = 'POOL_INVALID_REQUEST'; 
export const POOL_INTERNAL_SERVER_ERROR = 'POOL_INTERNAL_SERVER_ERROR';

export const QUOTE_UPDATE = 'QUOTE_UPDATE';
export const USER_UPDATE = 'USER_UPDATE';
export const DEALER_UPDATE = 'DEALER_UPDATE';
export const POOL_UPDATE = 'POOL_UPDATE';

export const SUCCESSFUL_QUOTE_CREATION = 'SUCCESSFUL_QUOTE_CREATION';
export const SUCCESSFUL_DEALER_CREATION = 'SUCCESSFUL_DEALER_CREATION';
export const SUCCESSFUL_POOL_CREATION = 'SUCCESSFUL_POOL_CREATION';
export const SUCCESSFUL_USER_CREATION = 'SUCCESSFUL_USER_CREATION';