export const SUCCESSFUL_LOGIN = 'SUCCESS_LOGIN';
export const FAILED_BAD_REQUEST = 'FAILED_BAD_REQUEST';
export const FAILED_INVALID_REQUEST = 'FAILED_INVALID_REQUEST'; 
export const FAILED_INTERNAL_SERVER_ERROR = 'FAILED_INTERNAL_SERVER_ERROR';