export const SUCCESSFUL_LOGIN = 'SUCCESS_LOGIN';
export const FAILED_BAD_REQUEST = 'FAILED_BAD_REQUEST';
export const FAILED_INVALID_REQUEST = 'FAILED_INVALID_REQUEST'; 
export const FAILED_INTERNAL_SERVER_ERROR = 'FAILED_INTERNAL_SERVER_ERROR';
export const SUCCESSFUL_LOGOUT = 'SUCCESSFUL_LOGOUT';

export const SUCCESSFUL_SIGNUP = 'SUCCESSFUL_SIGNUP';

export const SUCCESSFUL_CONTACT_CREATION = 'SUCCESSFUL_CONTACT_CREATION';